package initcmd

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/neural-chilli/qp/internal/config"
)

func mergeInferredCodemap(cfgPath string, inferred map[string]config.CodemapPackage) (string, error) {
	if len(inferred) == 0 {
		return "no codemap packages inferred", nil
	}

	raw, err := os.ReadFile(cfgPath)
	if err != nil {
		return "", err
	}
	content := string(raw)
	trimmed := strings.TrimSpace(content)
	if strings.Contains(content, "\ncodemap:") || strings.HasPrefix(trimmed, "codemap:") {
		return "qp.yaml already contains codemap; skipped inferred codemap append", nil
	}

	block := renderInferredCodemap(inferred)
	if strings.TrimSpace(content) == "" {
		content = block
	} else {
		content = strings.TrimRight(content, "\n") + "\n\n" + block
	}
	if err := os.WriteFile(cfgPath, []byte(content), 0o644); err != nil {
		return "", err
	}
	return fmt.Sprintf("added inferred codemap packages (%d)", len(inferred)), nil
}

func renderInferredCodemap(packages map[string]config.CodemapPackage) string {
	var builder strings.Builder
	builder.WriteString("# Generated by qp init --codemap — review and refine\n")
	builder.WriteString("codemap:\n")
	builder.WriteString("  packages:\n")

	names := make([]string, 0, len(packages))
	for name := range packages {
		names = append(names, name)
	}
	sort.Strings(names)

	for _, name := range names {
		pkg := packages[name]
		builder.WriteString(fmt.Sprintf("    %s:\n", name))
		builder.WriteString(fmt.Sprintf("      desc: %s\n", yamlQuote(pkg.Desc)))
		if len(pkg.KeyTypes) > 0 {
			builder.WriteString("      key_types:\n")
			for _, keyType := range pkg.KeyTypes {
				builder.WriteString(fmt.Sprintf("        - %s\n", yamlQuote(keyType)))
			}
		}
		if len(pkg.EntryPoints) > 0 {
			builder.WriteString("      entry_points:\n")
			for _, entry := range pkg.EntryPoints {
				builder.WriteString(fmt.Sprintf("        - %s\n", yamlQuote(entry)))
			}
		}
	}
	return builder.String()
}

func yamlQuote(value string) string {
	return "'" + strings.ReplaceAll(value, "'", "''") + "'"
}
